"""Method K3 -- Process I that is exact, unfragmented, and alias-free.

Fixes the two defects that made K2 lose 73x on wall-clock to target while
keeping the properties K2 got right.

WHAT K2 GOT RIGHT (kept)
    Parameter-keyed banking. Debt follows the parameter it was incurred for,
    so it survives arbitrary batch composition, ordering and duplication.

WHAT K2 GOT WRONG (fixed here)
    1. GEMM FRAGMENTATION. K2 advanced a separate cycle per parameter, so rows
       in one batch wanted different column groups and the single restricted
       GEMM shattered into up to G tiny ones, none reaching useful CPU
       throughput. Measured 0.05x the FLOPs of dense but 3.9x the WALL-CLOCK.

       K3 uses a GLOBAL group schedule: at any step every row in the batch is
       served the same column group, so there is exactly ONE GEMM per step,
       shaped (n x d_out) @ (d_out x k). FLOPs are unchanged; the work is one
       contiguous operation again.

    2. ALIASING. A round-robin global schedule reintroduces the rung-3e
       failure: a parameter touched with period P only ever meets groups
       generated by P in Z_G, i.e. a fraction 1/gcd(P, G) of them. Verified to
       four decimals in rung 3e.

       K3 draws the group order as a fresh random permutation of all G groups
       each cycle. There is no arithmetic relationship for an access period to
       resonate with, so no gcd can starve a parameter.

HOW EXACT DEBT SURVIVES A GLOBAL SCHEDULE
    Under a global schedule a parameter meets group g at irregular intervals,
    so a two-phase cycle (which K2 could use because its cycles were
    per-parameter) is no longer sufficient. K3 stores instead:

        T[r]      running sum of every gradient parameter r has received
        S[r][g]   snapshot of T[r] when r last received group g

        payout(r, g) = (T[r] - S[r][g]) @ W[:, cols_g]

    which is the EXACT sum of every gradient r accumulated since it last had
    group g repaid. Nothing is discarded and nothing is double counted,
    regardless of when r happens to be touched.

    Cost: (G + 1) * n_params * d_out of state. At keep=0.25 (G=4), V=256,
    d_out=512, float32 that is 2.6 MB against 1 MB of weights. Memory scales
    as 1/keep, so aggressive sparsity is what makes this expensive -- and
    aggressive sparsity is also what makes deferral inaccurate, so the two
    costs push the same way and the useful operating point is moderate keep.

ERROR
    The only error is staleness: a gradient is applied against the current W
    rather than the W in force when it was computed. There is no bias floor
    and nothing is dropped. Measured error falls monotonically as keep rises.
"""
from __future__ import annotations

import time as _time

import torch

from src.restricted_backward.methods import reference_forward


class GlobalScheduleAccumulation:
    """Process I: one GEMM per step, exact per-parameter debt, no aliasing."""

    name = "K3"

    def __init__(
        self,
        d_in: int,
        d_out: int,
        *,
        keep_fraction: float,
        n_params: int,
        dtype=torch.float32,
        seed: int = 0,
    ):
        g = torch.Generator().manual_seed(seed)
        self.W = torch.randn(d_out, d_in, generator=g, dtype=dtype) / d_in**0.5
        self.d_in, self.d_out, self.n_params = d_in, d_out, n_params
        self.k = max(1, int(round(keep_fraction * d_in)))
        self.n_groups = max(1, -(-d_in // self.k))

        # Contiguous column BLOCKS in the natural order. An earlier version
        # permuted the columns; that made W[:, cols] a cheap view but forced
        # the caller's update E[:, cols] -= vals into a fancy-index scatter,
        # measured at 0.469 ms against 0.055 ms for a contiguous slice -- a
        # 0.41 ms penalty per step that exceeded the 0.48 ms the restricted
        # GEMM saves. Only the SERVING ORDER needs to be random (to defeat the
        # gcd aliasing of rung 3e); which columns share a group is arbitrary,
        # so contiguous blocks are strictly better.
        bounds = [
            (i * self.k, min((i + 1) * self.k, d_in))
            for i in range(self.n_groups)
        ]
        self._bounds = bounds
        self.groups = [torch.arange(a, b) for a, b in bounds]

        self._rng = torch.Generator().manual_seed(seed + 7717)
        self._order = self._new_order()
        self._pos = 0

        # T[r] and one snapshot per (parameter, group).
        self._total = torch.zeros(n_params, d_out, dtype=dtype)
        self._snap = torch.zeros(self.n_groups, n_params, d_out, dtype=dtype)
        self._debt = torch.zeros(n_params, d_out, dtype=dtype)
        self._step = 0
        self.max_backward_tensor_bytes = 0
        self.aux_bytes = (
            self._total.numel() + self._snap.numel()
        ) * self._total.element_size()

    def _new_order(self) -> list[int]:
        """Fresh random permutation of the groups for the next cycle."""
        return torch.randperm(self.n_groups, generator=self._rng).tolist()

    def forward(self, X: torch.Tensor) -> torch.Tensor:
        return reference_forward(X, self.W)

    @property
    def visit_period(self) -> int:
        """Every group is served exactly once per G steps, in random order."""
        return self.n_groups

    def backward(self, G_Y: torch.Tensor, ids: torch.Tensor | None = None):
        """Returns ((a, b), vals): the update for the CONTIGUOUS column slice
        [a, b). `ids=None` means full-batch, the regime Process I serves in a
        transformer, and takes a path with no gather or scatter at all.
        """
        elem = G_Y.element_size()

        _f0 = _time.perf_counter()
        if self._pos == len(self._order):
            self._order = self._new_order()
            self._pos = 0
        gi = self._order[self._pos]
        self._pos += 1
        a, b = self._bounds[gi]
        snap = self._snap[gi]

        if ids is None:
            self._total += G_Y
            torch.sub(self._total, snap, out=self._debt)
            snap.copy_(self._total)
            debt = self._debt
        else:
            self._total.index_add_(0, ids, G_Y)
            cur = self._total[ids]
            debt = cur - snap[ids]
            snap[ids] = cur
        feedback_s = _time.perf_counter() - _f0

        _g0 = _time.perf_counter()
        vals = debt @ self.W[:, a:b]             # ONE GEMM, contiguous view
        gemm_s = _time.perf_counter() - _g0

        self._step += 1
        self.max_backward_tensor_bytes = max(
            self.max_backward_tensor_bytes, vals.numel() * elem
        )
        executed = 2.0 * G_Y.shape[0] * self.d_out * (b - a)
        return ((a, b), vals), executed, 0.0, feedback_s, gemm_s

    @staticmethod
    def densify(packed, shape, dtype=torch.float32) -> torch.Tensor:
        (a, b), vals = packed
        out = torch.zeros(shape, dtype=dtype)
        out[:, a:b] = vals
        return out

    def exact_dX(self, G_Y: torch.Tensor) -> torch.Tensor:
        """Oracle for error measurement only. Never in a timed path."""
        return G_Y @ self.W

    def apply_dense_dW(self, dW: torch.Tensor, lr: float) -> None:
        self.W -= lr * dW

    def param_bytes(self) -> int:
        return self.W.numel() * self.W.element_size()
